packages:
  formulae:
    - dnscrypt-proxy
  casks:
    - gswitch
    - notion
    - rawtherapee
    - shadow
    - steam
    - steermouse
    - todoist-app
    - whatsapp
    - protonvpn

post_install:
  - sudo brew services start dnscrypt-proxy
