taps:
  - caarlos0/tap

packages:
  formulae:
    # üñ•Ô∏è System Utilities
    - blueutil
    - brightness
    - exiftool
    - fastfetch
    - fd
    - ffmpeg
    - fzf
    - gifsicle
    - glances
    - gnu-sed
    - grep
    - htmlcompressor
    - htop
    - btop
    - bottom
    - iftop
    - less
    - lsd
    - make
    - mozjpeg
    - ncdu
    - p7zip
    - pcre2
    - pv
    - pwgen
    - rename
    - ripgrep
    - ssh-copy-id
    - tree
    - viddy
    - z

    # üîê Security & Productivity Additions
    - navi
    - tealdeer
    - gitleaks
    - trivy
    - gping
    - bandwhich
    - yq

    # üåê Networking Tools
    - curl
    - dnsmasq
    - lsof
    - mtr
    - rclone
    - rsync
    - syncthing
    - wget

    # üóÇÔ∏è Git & Version Control
    - difftastic
    - gh
    - git
    - git-delta
    - gitui
    - lazygit
    - spr
    - tig

    # ‚úçÔ∏è Editors
    - neovim

    # üßë‚Äçüíª Programming Languages & Runtimes
    - node
    - python
    - ruby
    - readline
    - xz
    - zlib

    # üß∞ Other Tools & Utilities
    - antidote
    - asciinema
    - bat
    - biome
    - duf
    - dust
    - hyperfine
    - procs
    - sd
    - tokei
    - viu
    - ffmpegthumbnailer
    - mise

    - git-recent
    - glow
    - gnupg
    - heroku
    - httpie
    - imagemagick
    - ipcalc
    - jesseduffield/lazynpm/lazynpm
    - jless
    - jnv
    - jq
    - mas
    - molovo/revolver/revolver

    - openssl@3
    - pandoc
    - poppler

    - tcl-tk

    - subversion
    - switchaudio-osx
    - trdsql
    - unar
    - xcodes
    - yarn
    - yazi
    - yt-dlp
    - silicon
    - glow
    - imagineer
    - gonzo

  casks:
    # ‚ö° Productivity & Utilities
    - altair-graphql-client
    - android-commandlinetools
    - android-studio
    - bruno
    - cap
    - claude
    - cleanshot
    - discord
    - espanso
    - etrecheckpro
    - firefox@nightly
    - fliqlo
    - flux-app
    - google-chrome@canary
    - grandperspective
    - image2icon
    - imageoptim
    - insomnia
    - iterm2@nightly
    - jordanbaird-ice
    - keepassxc
    - loom
    - macmediakeyforwarder
    - middleclick
    - minisim
    - mitmproxy
    - monitorcontrol
    - monodraw
    - notion-calendar
    - obsidian
    - openmtp
    - osquery
    - pika
    - pixelsnap
    - prefs-editor
    - proxyman
    - qr-journal
    - raycast
    - react-native-debugger
    - runjs
    - signal
    - slack
    # - spotify
    - qobuz
    - stats
    - sublime-merge@dev
    - syncthing-app
    - upscayl
    - visual-studio-code
    - vlc
    - xcodes-app
    - xquartz
    - localsend
    - opcode
    - caarlos0/tap/svu
    - superwhisper

    # üî§ Fonts
    - font-symbols-only-nerd-font
    - font-3270-nerd-font
    - font-arimo-nerd-font
    - font-cascadia-code
    - font-cascadia-mono
    - font-cousine-nerd-font
    - font-fira-code
    - font-go-mono-nerd-font
    - font-hack-nerd-font
    - font-hubot-sans
    - font-inconsolata-nerd-font
    - font-iosevka-nerd-font
    - font-jetbrains-mono
    - font-jetbrains-mono-nerd-font
    - font-lekton-nerd-font
    - font-mona-sans
    - font-monofur-nerd-font
    - font-monoid-nerd-font
    - font-mononoki-nerd-font
    - font-noto-nerd-font
    - font-profont-nerd-font
    - font-tinos-nerd-font
    - font-ubuntu
    - font-ubuntu-mono-derivative-powerline
    - font-ubuntu-nerd-font

    # üëÅÔ∏è QuickLook Plugins
    - qlvideo
    - suspicious-package

post_install:
  # System configuration
  - brew link --overwrite node
  - xattr -d -r com.apple.quarantine ~/Library/QuickLook
